### ISSUE TITLE
Global Dexter.restore()

### ISSUE THREAD

**Issue by sobrinho** [leobalter/DexterJS#5]
Hi,

I would to suggest a global `Dexter.restore()` that can be used to restore all called stubs instead of invoking it one by one.

This will make more easier to use DexterJS using a hook like this:

``` javascript
describe("something", function () {
  after(function () {
    Dexter.restore();
  });

  it("should do something", function () {
    Dexter.stub( window, 'something', function() {
      return 10;
    });

    window.something.should.equal(10);
  });

  it("should do something else", function () {
    Dexter.stub( window, 'something', function() {
      return 20;
    });

    window.something.should.equal(20);
  });
});
```

If you agree, I would to make a pull request :)

**Comment by leobalter** [comment]
It´s great as the pull request would be as well. Send it, please!

**Comment by leobalter** [comment]
Sorry for the insanely huge delay, but it's done (still on branch 0.4.0) :)
